### ISSUE TITLE
Package build error

### ISSUE THREAD

**Issue by falzm** [bcandrea/consul-deb#1]
Hi

I'm trying to build the package using pbuilder for Debian wheezy – I backported `golang-go` 1.3.2 –, but I the build processes fails:

```
make[1]: Entering directory `/tmp/buildd/consul-0.4.1'
make[1]: Nothing to be done for `build'.
make[1]: Leaving directory `/tmp/buildd/consul-0.4.1'
   dh_testdir
   dh_auto_configure
   debian/rules override_dh_auto_build
make[1]: Entering directory `/tmp/buildd/consul-0.4.1'
export GOPATH=/tmp/buildd/consul-0.4.1 && /usr/bin/make -C src/github.com/hashicorp/consul
make: Entering an unknown directory
make: *** src/github.com/hashicorp/consul: No such file or directory.  Stop.
make: Leaving an unknown directory
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory `/tmp/buildd/consul-0.4.1'
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

Sorry for no being more verbose, I'm quite a noob in Debian packaging. Let me know if I can provide any more details on my setup.

**Comment by bcandrea** [comment]
Hi,

Sorry for not getting back to you, but I had trouble to reproduce builds as well. I then decided to start using `git-buildpackage` and Docker; hopefully it will be much easier to get a pristine build environment now.
