### ISSUE TITLE
PPA outdated?

### ISSUE THREAD

**Issue by rkrzr** [bcandrea/consul-deb#7]
Hi,

thanks for providing this script.
I was looking for a PPA for consul and yours is the top hit on Google, but it seems that it is not maintained any more, is that right?

The latest consul version seems to be 0.6.3, while the PPA packages 0.4.1.

Are you considering packaging a new version as well?

**Comment by bcandrea** [comment]
Hi @rkrzr, 

I decided to spend some time restructuring the repo first, in order to be able to build the package using Docker.

I just uploaded v0.6.4 to my PPA (for Trusty, Wily and Xenial).

Hope this helps.
